### ISSUE TITLE
Installation Instructions are incomplete

### ISSUE THREAD

**Issue by phdoerfler** [JensForstmann/factorio-blueprint-tools#1]
I have this `.npmrc` in my project directory:

```
@jensforstmann:registry=https://npm.pkg.github.com
```

Issuing this command:

```
npm install @jensforstmann/factorio-blueprint-tools
```

results in:

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

Disclaimer: I normally avoid anything JS like the plague so please bear with me if I'm missing something obvious.

**Comment by phdoerfler** [comment]
Looks like even for installing packages one has to authenticate. What a hassle.

I got two suggestions if I may:
- Simply link to https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages instead of the existing instructions about how to add the github registry.
- Ditch the registries altogether and document this instead:
```npm install git+https://github.com/jensforstmann/factorio-blueprint-tools.git```
or don't, because that doesn't work out of the box either:
```npm ERR! prepareGitDep 2> Error: Failed to replace env in config: ${NPM_TOKEN}```
/sighs/

**Comment by JensForstmann** [comment]
Thanks for the feedback, I'll update the docs to make it easier.

For your second suggestion:
I removed the `.npmrc` file from this repo which points to an env var. I used it instead of my user's config file. So this should work now:

    npm install git+https://github.com/jensforstmann/factorio-blueprint-tools.git

or in short:

    npm install github:jensforstmann/factorio-blueprint-tools

Keep in mind that then npm will always install the latest version (master branch) no matter if there were any breaking changes.
If the git repo provides tags according to semver you can use that in the url as well.
If you want to NOT update to new major versions:

    npm install github:jensforstmann/factorio-blueprint-tools#semver:^1.2.2

https://docs.npmjs.com/cli/v7/commands/npm-install

**Comment by JensForstmann** [comment]
@phdoerfler
I've added a seperate prerequisites section into the README.md
https://github.com/JensForstmann/factorio-blueprint-tools#prerequisites
Hoping it is now more clear.

>Looks like even for installing packages one has to authenticate. What a hassle.

Yes indeed, I hope they will lift this restriction in the future.

**Comment by JensForstmann** [comment]
@phdoerfler 

Not sure if you still have any interest in it, but:
I moved the package to npmjs so no Github auth is required to install it.

Simply ditch your `.npmrc` file (or at least the line with `@jensforstmann:registry=https://npm.pkg.github.com`) and do `npm install @jensforstmann/factorio-blueprint-tools`.
This will laod the latest version (1.25) from npmjs.

**Comment by phdoerfler** [comment]
@JensForstmann Thanks! I’m still very much interested and plan on using this library more in the future but for now I have to save my time for more pressing things such as my master thesis 😉
